baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'la'

[[menu.nav]]
name = "About"
url = "/about/"
weight = 5
[menu.nav.params]
information = true

[[menu.nav]]
name = "Services"
url = "/services/"
weight = 5

[[menu.nav]]
name = "Gallery"
url = "/gallery/"
weight = 5
[menu.nav.params]
more = true

[[menu.nav]]
name = "Contact"
url = "/contact/"
weight = 5
[menu.nav.params]
information = true

[[menu.nav]]
name = "Testimonials"
url = "/testimonials/"
weight = 5
[menu.nav.params]
more = true

[[menu.footer]]
name = "Personal Training"
url = "/personal-training/"
weight = 5

[[menu.footer]]
name = "Kids Clubs"
url = "/kids-clubs/"
weight = 5

[[menu.footer]]
name = "Special Events"
url = "/special-events/"
weight = 5

[[menu.footer]]
name = "Sports Development Coaching"
url = "/sports-development-coaching/"
weight = 5

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[module]
[module.hugoVersion]
extended = false
min = "0.116.0"
