baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'la'

[[menu.nav]]
name = "ABOUT"
url = "/about/"
weight = 5

[[menu.nav]]
name = "SERVICES"
url = "/services/"
weight = 5

[[menu.nav]]
name = "GALLERY"
url = "/gallery/"
weight = 5

[[menu.nav]]
name = "CONTACT"
url = "/contact/"
weight = 5

[[menu.nav]]
name = "TESTIMONIALS"
url = "/testimonials/"
weight = 5

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[module]
[module.hugoVersion]
extended = false
min = "0.116.0"
